# Generated by Django 4.1.5 on 2023-01-12 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_login', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='UserSignUp',
        ),
        migrations.AlterModelOptions(
            name='usersignup',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='Address',
            new_name='address',
        ),
    ]
