# Generated by Django 4.1.5 on 2023-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_rename_signup_usersignup_alter_usersignup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='password',
            field=models.CharField(blank=True, max_length=265),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='username',
            field=models.CharField(blank=True, max_length=265),
        ),
    ]
