# Generated by Django 4.1.5 on 2023-01-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0004_usersignup_password_usersignup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='username',
        ),
    ]
