# Generated by Django 4.1.5 on 2023-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0005_remove_usersignup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='password',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
